import type { Metadata } from "next";
import { Lato, Poppins, Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Logo from "./components/Logo";
import Footer from "./components/Footer";

const lato_init = Lato ({
  subsets: ['latin'],
  weight: ["100", "300", "400", "700", "900"],
  variable :'--font-lato'
})

const poppins_init = Poppins ({
  subsets: ['latin'],
  weight: ["100","200","300", "400", "500", "600", "700", "800", "900"],
  variable :'--font-poppins'
})

const kanit_init = Kanit ({
  subsets: ['latin'],
  weight: ["100","200","300", "400", "500", "600", "700", "800", "900"],
  variable :'--font-kanit'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato_init.variable} ${poppins_init.variable} ${kanit_init.variable} antialiased`}
      >
        <div className="nav-container relative w-full h-auto flex">
          <div className=""></div>
          <Logo/>
            <Navbar/>
          </div>
          <main className="flex flex-wrap h-[auto] w-full">
          <div className="fixed h-screen overflow-hidden w-screen">
      <img
        id="heroImage"
        src="/geometric_shapes.jpeg"
        alt="Hero Businessman"
        className="absolute inset-0 w-full h-full object-cover z-0"
      />
      </div>
            {children}
           
          </main>

      <Footer/>
      </body>
    </html>
  );
}
